name: Deploy to Railway

on:
  push:
    branches:
      - backend/dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean install --file backend/pom.xml

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          curl -sL https://railway.app/cli | sh
          railway login --token $RAILWAY_TOKEN
          railway up --service-name justina --build-cmd "mvn clean install -DskipTests" --start-cmd "java -jar backend/target/justina.jar"
