name: Deploy Backend to Render

on:
  push:
    branches:
      - backend/dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: backend  # Se asegura de que se verifique solo el código en la carpeta backend

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        working-directory: backend  # Se asegura de que se construya solo dentro de la carpeta backend
        run: ./mvnw clean install

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        working-directory: backend  # Se asegura de que se construya y se empuje solo dentro de la carpeta backend
        run: |
          docker build . -t your-dockerhub-username/justina:latest
          docker push your-dockerhub-username/justina:latest

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          API_SECRET: ${{ secrets.API_SECRET }}
        run: |
          curl -X POST "https://api.render.com/deploy/srv-cqbc5688fa8c73b5s7n0?key=Sz3XJC3Kn4M" \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Accept: application/json" \
          -H "Content-Type: application/json" \
          --data '{"clearCache":false}'
